/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/TaskContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AddTask` | `/AddTask`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Details` | `/Details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/List` | `/List`; params?: Router.UnknownInputParams; } | { pathname: `/components/TaskActions`; params?: Router.UnknownInputParams; } | { pathname: `/components/TaskDetails`; params?: Router.UnknownInputParams; } | { pathname: `/components/TaskForm`; params?: Router.UnknownInputParams; } | { pathname: `/components/TaskList`; params?: Router.UnknownInputParams; } | { pathname: `/components/TaskSummary`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/TaskContext`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/AddTask` | `/AddTask`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Details` | `/Details`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/List` | `/List`; params?: Router.UnknownOutputParams; } | { pathname: `/components/TaskActions`; params?: Router.UnknownOutputParams; } | { pathname: `/components/TaskDetails`; params?: Router.UnknownOutputParams; } | { pathname: `/components/TaskForm`; params?: Router.UnknownOutputParams; } | { pathname: `/components/TaskList`; params?: Router.UnknownOutputParams; } | { pathname: `/components/TaskSummary`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/TaskContext${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/AddTask${`?${string}` | `#${string}` | ''}` | `/AddTask${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Details${`?${string}` | `#${string}` | ''}` | `/Details${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/List${`?${string}` | `#${string}` | ''}` | `/List${`?${string}` | `#${string}` | ''}` | `/components/TaskActions${`?${string}` | `#${string}` | ''}` | `/components/TaskDetails${`?${string}` | `#${string}` | ''}` | `/components/TaskForm${`?${string}` | `#${string}` | ''}` | `/components/TaskList${`?${string}` | `#${string}` | ''}` | `/components/TaskSummary${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/TaskContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AddTask` | `/AddTask`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Details` | `/Details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/List` | `/List`; params?: Router.UnknownInputParams; } | { pathname: `/components/TaskActions`; params?: Router.UnknownInputParams; } | { pathname: `/components/TaskDetails`; params?: Router.UnknownInputParams; } | { pathname: `/components/TaskForm`; params?: Router.UnknownInputParams; } | { pathname: `/components/TaskList`; params?: Router.UnknownInputParams; } | { pathname: `/components/TaskSummary`; params?: Router.UnknownInputParams; };
    }
  }
}
